# Set Travis-CI build language to JavaScript (with NodeJS)
language: node_js

# Switch Sudo off to use Travi's new and fast Docker infrastructure
sudo: false

before_install: npm install -g grunt-cli
